### ISSUE TITLE
Jelesert

### ISSUE THREAD

**Issue by hegyhati** [horvathfanni/Donteselokeszites#2]
- tobb pocsagatipus (bemenetben, es figyelni, hogy mindenconstraintben le legyen kezelve)
- autotulajdonsagok kigazolasa (vagy 1 van, vagy tobb, de akkor rendesen)
- Meg valami plusz

**Comment by hegyhati** [comment]
@horvathfanni ezzel akkor nem dolgozol?

**Comment by HorvathFanni** [comment]
@hegyhati Sajnos nem maradt rá elég időm :(

**Comment by hegyhati** [comment]
@horvathfanni Van ez igy, hajra a tobbi vizsgahoz akkor :-)
